server {
    listen 5500;
    server_name _;

    root /usr/share/nginx/html;
    index static/house.html;

    location / {
        try_files $uri $uri/ /static/house.html;
    }

    location /static/ {
        try_files $uri =404;
    }
}
